artist/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

from django.contrib.auth import views as auth_views
from allauth.account.views import LoginView

from django.contrib.sitemaps.views import sitemap
from artevenue.sitemaps import *
sitemaps = {
   'static': StaticSitemap(),
}


urlpatterns = [
	
	url(r'^create-artist-group/$', views.create_artist_group, name='create_artist_group'),
	#url(r'^artist-signup/$', views.register_as_artist, name='artist_signup'),
	url(r'^artist-signup/$', views.coming_soon, name='artist_signup'),
	path('artist-registration-confirmation/<int:id>', views.artist_registration_confirmation, name='artist_registration_confirmation'),
	path('artist/<str:url_name>', views.artist_webpage, name='artist_webpage'),
	url(r'^artist-profile/$', views.create_artist_profile, name='artist_profile'),
	url(r'^ajax/upload-artist-photo/$', views.upload_artist_photo, name='upload_artist_photo'),
	url(r'^ajax/validate-url-name/$', views.validate_url_name, name='validate_url_name'),
	url(r'^ajax/save-artist-profile/$', views.save_artist_profile, name='save_artist_profile'),

	url(r'^product-original-art/$', views.original_art_detail, name='original_art_detail'),
	path('product-original-art/<int:prod_id>/', views.original_art_detail, name='original_art_detail'),	

	url(r'^original-art-by-category/$', views.get_original_arts, name='original_art_by_category'),
	path('original-art-by-category/<str:cat_nm>/', views.get_original_arts, name='original_art_by_category'),
	path('original-art-by-category/<str:cat_nm>/<int:page>', views.get_original_arts, name='original_art_by_category'),

	url(r'^show-all-original-art-categories/$', views.show_all_original_art_categories, name='show_all_original_art_categories'),


	url(r'^upload-art/$', views.upload_art, name='upload_art'),
	path('upload-art/<str:part_number>/', views.upload_art, name='upload_art'),

	url(r'^original-artwork-approval/$', views.original_artwork_approval, name='original_artwork_approval'),
	url(r'^ajax/set-original-artwork-approval/$', views.set_original_artwork_approval, name='set_original_artwork_approval'),
	
	url(r'^get-my-artworks/$', views.get_my_artworks, name='get_my_artworks'),
	path('delist-artwork/<str:part_number>/', views.delist_artwork, name='delist_artwork'),

	#url(r'^artist-page/$', views.artist_page, name='artist_page'),
	url(r'^artist-page/$', views.coming_soon, name='artist_page'),
	url(r'^artist-terms/$', views.artist_terms, name='artist_terms'),

	#url(r'^original-art-by-category/$', views.get_original_arts, name='original_art_by_category'),
	#path('original-art-by-category/<int:cat_id>/', views.get_original_arts, name='original_art_by_category'),
	#path('original-art-by-category/<int:cat_id>/<int:page>', views.get_original_arts, name='original_art_by_category'),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

from django.contrib.auth import views as auth_views
from allauth.account.views import LoginView

from django.contrib.sitemaps.views import sitemap


urlpatterns = [
	
	#url(r'^artist_signup/$', views.register_as_artist, name='artist_signup'),
	url(r'^blog/$', views.blog, name='blog'),
	path('get-blog/<int:post_id>', views.get_blog, name='get_blog'),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

estore/urls.py
from django.contrib import admin
from django.conf.urls import include, url

from django.urls import path

from rest_framework import routers
from artevenue.views import api_views

router = routers.DefaultRouter()
router.register(r'homelane', api_views.Homelane_dataViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('artevenue.urls')),
    url('^', include('artist.urls')),
	url('^', include('review.urls')),
    url('^', include('gallerywalls.urls')),
    url('^', include('returns.urls')),
    url('^', include('av_products.urls')),
    url('^', include('spinwheel.urls')),
	url(r'', include('webmaster_verification.urls')),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	
	url(r'^tinymce/', include('tinymce.urls')),
    url('^', include('blog.urls')),	
]

artist/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.fields import DecimalField

from artevenue.models import Ecom_site, Product_type, Original_art, Order_items_view, Product_view, Order


class Artist_group (models.Model):
	REF_TYPE = (
		('PERCETNAGE', 'Percentage of Sale Price'),
		('FLAT', 'Flat Fee'),
	)	
	group_id = models.CharField(primary_key=True, max_length=10, null=False)
	name = models.CharField(max_length=256, blank=False,  default='')
	original_referral_fee_type = models.CharField(max_length=10, 
		choices = REF_TYPE, null=True)
	original_art_referral_fee = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	art_print_referral_fee_type = models.CharField(max_length=10, 
		choices = REF_TYPE, null=True)
	art_print_referral_fee = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	created_date = models.DateTimeField(auto_now_add=True, null=False)	
	updated_date = models.DateTimeField(auto_now=True, null=False)	
	
	def __str__(self):
		return self.name
	
class Artist (models.Model):
	artist_id = models.AutoField(primary_key=True, max_length=10, null=False)
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	phone_number = models.CharField(max_length=15, blank=False, default='')
	alternate_phone_number = models.CharField(max_length=15, blank=False, default='')
	address1 = models.CharField(max_length = 1000 , blank=True, default='')
	address2 = models.CharField(max_length = 1000 , blank=True, default='')	
	city = models.CharField(max_length = 256 , blank=True, default='')
	state = models.CharField(max_length = 256 , blank=True, default='')	
	pin_code = models.CharField(max_length = 256 , blank=True, default='')	
	country = models.CharField(max_length = 256 , blank=True, default='')		
	artist_group = models.ForeignKey(Artist_group, models.SET_NULL, null=True, blank=True)
	artist_profile = models.CharField(max_length=2000, blank=False, default='')
	artist_showcase1_name = models.CharField(max_length=50, blank=False, default='')
	artist_showcase1 = models.CharField(max_length=2000, blank=False, default='')
	artist_showcase2_name = models.CharField(max_length=50, blank=False, default='')
	artist_showcase2 = models.CharField(max_length=2000, blank=False, default='')
	artist_showcase3_name = models.CharField(max_length=50, blank=False, default='')
	artist_showcase3 = models.CharField(max_length=2000, blank=False, default='')
	profile_name = models.CharField(max_length=200, blank=False, default='') ## use for display (ex. Jaideep Kumar)
	url_name = models.CharField(max_length=50, blank=False, default='')  ## used for creating url (ex. 'jaideep_kumar' in https://www.artevenue.com/artist/jaideep_kumar)
	profile_photo = models.ImageField(upload_to='artist/profile_photo/%Y/%m/%d/', blank=True, default="")
	profile_tagline = models.CharField(max_length=500, blank=False, default='')
	publisher = models.ForeignKey('artevenue.Publisher', models.CASCADE, null=True)
	store = models.ForeignKey('artevenue.Ecom_site', models.CASCADE, null=False)
	gallary_url = models.CharField(max_length = 1000, blank=True, default='')
	default_original_art_price = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)	
	created_date = models.DateTimeField(auto_now_add=True, null=False)	
	updated_date = models.DateTimeField(auto_now=True, null=False)	
	approved = models.BooleanField(null=False, default=False)
	approval_date =  models.DateTimeField(blank=True, null=True)
	
	def __str__(self):
		return self.first_name + " " + self.last_name

	def save(self, *args, **kwargs):
		if self.profile_photo:
			self.create_thumbnail()
			
		super(Artist, self).save()	

	def create_thumbnail(self):
		from PIL import Image, ExifTags
		from io import BytesIO
		import os
		# If there is no image associated with this.
		# do not create thumbnail
		if not self.profile_photo:
			return

		# Set our max thumbnail size in a tuple (max width, max height)
		THUMBNAIL_SIZE = (200,200)
		PIL_TYPE = ''
		if self.profile_photo.name.lower().endswith(".jpg"):
			PIL_TYPE = 'jpeg'
			FILE_EXTENSION = 'jpg'
			DJANGO_TYPE = 'image/jpeg'
		if self.profile_photo.name.lower().endswith(".png"):
			PIL_TYPE = 'png'
			FILE_EXTENSION = 'png'
			DJANGO_TYPE = 'image/png'
		if self.profile_photo.name.lower().endswith(".gif"):
			PIL_TYPE = 'gif'
			FILE_EXTENSION = 'gif'
			DJANGO_TYPE = 'image/gif'
		if PIL_TYPE == '' :
			extension = os.path.splitext(self.profile_photo.name)[1]
			PIL_TYPE = extension.lower()[1:]
			FILE_EXTENSION = PIL_TYPE
			DJANGO_TYPE = 'image/' + PIL_TYPE[1:]

		# Open original photo which we want to thumbnail using PIL's Image
		image = Image.open(self.profile_photo)
			
		# use our PIL Image object to create the thumbnail, which already
		image.thumbnail(THUMBNAIL_SIZE, Image.ANTIALIAS)

		# Save the thumbnail
		temp_handle = BytesIO()		
		image.save(temp_handle, PIL_TYPE)
		temp_handle.seek(0)
		
		# Save image to a SimpleUploadedFile which can be saved into ImageField
		from django.core.files.uploadedfile import SimpleUploadedFile
		suf = SimpleUploadedFile(os.path.split(self.profile_photo.name)[-1],
								 temp_handle.read(), content_type=DJANGO_TYPE)
		# Save SimpleUploadedFile into image field
		self.profile_photo.save(
			'%s_thumbnail.%s' % (os.path.splitext(suf.name)[0], FILE_EXTENSION),
			suf, save=False)



class Artist_sms_email(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=False)
	msg_type = models.CharField(max_length = 20, blank=True, default='NEW-ACCNT')
	email_sent = models.BooleanField(null=False, default=False)
	sms_sent = models.BooleanField(null=False, default=False)
	created_date = models.DateTimeField(auto_now_add=True, null=False)	
	updated_date = models.DateTimeField(auto_now=True, null=False)


class Artist_stock_image (models.Model):
	artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
	product = models.ForeignKey('artevenue.Stock_image', models.PROTECT, null=False)
	artist_listed = models.BooleanField(null=False, default=False)
	approved = models.BooleanField(null=False, default=False)
	approval_date = models.DateTimeField(null = True)
	created_date = models.DateTimeField(auto_now_add=True, null=False)	
	updated_date = models.DateTimeField(auto_now=True, null=False)	
	unapproved = models.BooleanField(null=False, default=False)
	unapproval_date = models.DateTimeField(null = True)


class Artist_original_art (models.Model):
	SELL_MODE = (
		('O', 'ONLY ORIGINAL'),
		('A', 'ONLY ART PRINT'),
		('B', 'BOTH'),
	)
	REASON =  (
		('I', 'Artwork image is not fit for listing, Please upload another image. Follow image guidelines.'),
		('X', 'Artwork not found fit for listing'),
		('O', 'Other reason (Please get in touch with us)'),
	)
	artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
	product = models.ForeignKey('artevenue.Original_art', models.PROTECT, null=False)
	sell_mode = models.CharField(max_length=1, choices = SELL_MODE, null=True)
	artist_listed = models.BooleanField(null=False, default=False)
	uploaded_date = models.DateField(null = True)
	approved = models.BooleanField(null=False, default=False)
	approval_date = models.DateTimeField(null = True)
	created_date = models.DateTimeField(auto_now_add=True, null=False)	
	updated_date = models.DateTimeField(auto_now=True, null=False)	
	unapproved = models.BooleanField(null=False, default=False)
	unapproval_date = models.DateTimeField(null = True)
	unapproval_reason = models.CharField(max_length=1, choices = REASON, null=False, default = '')
	artist_price = models.DecimalField(max_digits=12, decimal_places=2, null=True)


class Inventory_udate(models.Model):
	product = models.ForeignKey(Original_art, models.PROTECT, null=False)
	product_type = models.ForeignKey('artevenue.Product_type', null=True, on_delete=models.SET_NULL)
	update_qty = models.IntegerField(null=False)	
	created_date = models.DateTimeField(auto_now_add=True, null=False)	
	updated_date = models.DateTimeField(auto_now=True, null=False)	

	def __str__(self):
		return str(self.product) + str(updated_qty)

class Generate_art_number(models.Model):
	NUM_TYPE = (
		('PART', 'Part Number'),
		('ORIG', 'Original ID'),
		('STKI', 'Stock Image ID'),
	)

	publisher = models.CharField(max_length = 20, null=False)
	type = models.CharField(max_length = 4, choices = NUM_TYPE, null=False)
	prefix = models.CharField(max_length = 10, null=False) 
	suffix = models.CharField(max_length = 10, null=False, default = '')
	current_number = models.IntegerField(null=False)	

	def __str__(self):
		return self.type + ", " + self.publisher + ', ' + self.prefix + str(current_number) + ', ' + self.suffix


class Artist_sales(models.Model):
	artist = models.ForeignKey(Artist, on_delete=models.CASCADE) 
	product_id = models.IntegerField(null=False, default = 0)		## USE THIS TO REFER TO PRODUCT_VIEW ALONG WITH PRODUCT_TYPE
	product_type = models.ForeignKey(Product_type, models.CASCADE, null=True)
	part_number = models.CharField(max_length = 30, null=True)
	order = models.ForeignKey(Order, models.PROTECT, null=False)
	order_item_id = models.IntegerField(null=False, default = 0) ## USE THIS TO REFER TO ORDER_ITEMS_VIEW
	sale_value = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	license_fee = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	pay_date = models.DateField(null = True)
	pay_reference = models.CharField(max_length = 100, null=True)
	created_date = models.DateTimeField(auto_now_add=True, null=False)	
	updated_date = models.DateTimeField(auto_now=True, null=False)	
	
	
	def __str__(self):
		return self.artist + " - " + self.part_number + " - " + str(sale_value)
		
		

artist/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from django.contrib.auth.models import User

from tinymce.widgets import TinyMCE

from artist.models import Artist_group, Artist
from artevenue.models import Ecom_site, Publisher

from artevenue.validators import validate_image_size, validate_india_mobile_no

ecom = Ecom_site.objects.get(pk=settings.STORE_ID )

class artistGroupForm(forms.ModelForm):
	class Meta:
		model = Artist_group
		fields = ('group_id','name', 'original_referral_fee_type', 'original_art_referral_fee',
				 'art_print_referral_fee_type', 'art_print_referral_fee')


class artistUserForm(UserCreationForm):
	email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
	class Meta:
		model = User
		fields = ('username','first_name', 'last_name', 'email', 'password1', 
				 'password2')

class artistRegisterForm(forms.ModelForm):
	store = forms.CharField(
		widget=forms.HiddenInput(),
		required=False
	)
	artist_group = forms.CharField(
		widget=forms.HiddenInput(),
		required=False
	)
	artist_profile = forms.CharField(
		widget=forms.HiddenInput(),
		required=False
	)
	publisher = forms.CharField(
		widget=forms.HiddenInput(),
		required=False
	)
	gallary_url = forms.CharField(
		widget=forms.HiddenInput(),
		required=False
	)
	default_original_art_price= forms.CharField(
		widget=forms.HiddenInput(),
		required=False
	)
	address_1 = forms.CharField(
		widget=forms.TextInput(attrs={'placeholder': 'Suit / Floor / Building'}),
		required=True
	) 
	address_2 = forms.CharField(
		widget=forms.TextInput(attrs={'placeholder': 'Street / Locality'}),
		required=False
	) 
	pin_code = forms.CharField(
		widget=forms.TextInput(),
		required=False
	)	
	city = forms.CharField(
		widget=forms.TextInput(),
		required=True
	)		
	phone_number= forms.CharField( widget=forms.TextInput(
		attrs={'placeholder': 'Enter your 10 digit mobile number without prefix +91, or 0.'}
		),
		required=True,
		validators=[validate_india_mobile_no]
	)
	alternate_phone_number= forms.CharField( widget=forms.TextInput(
		attrs={'placeholder': 'Enter your 10 digit mobile number without prefix +91, or 0.'}
		),
		required=False,
		validators=[validate_india_mobile_no]
	)
	
	def clean_artist_group(self):
		try:
			grp= Artist_group.objects.get(pk = 'GEN')
		except grp.DoesNotExist:
			grp = None
		return grp
		
	def clean_artist_profile(self):
		return ''

	def clean_publisher(self):
		try:
			pub= Publisher.objects.get(pk = '01')
		except Publisher.DoesNotExist:
			pub = None
		return pub
		
	def clean_gallary_url(self):
		return ''

	def clean_default_original_art_price(self):
		return None
	
	def clean_store(self):
		return ecom

	class Meta:
		model = Artist
		fields = ('address1', 'address2', 'city', 'state', 'pin_code','country', 'store',
		'phone_number', 'alternate_phone_number',
		'artist_group', 'artist_profile', 'publisher', 'gallary_url',
		'default_original_art_price')
				

class artistProfileForm(forms.ModelForm):
	artist_profile = forms.CharField(widget=TinyMCE(attrs={'cols': 100, 'rows': 12}),
						#widget=forms.TextInput(attrs={'readonly':'readonly'})
						)
	
	class Meta:
		model = Artist
		fields = ('artist_profile', 'gallary_url')

	

artist/templates/artist/artist_artworks.html
{% extends 'artevenue/estore_base.html' %}
{% load static %}
{% load utils %}
{% load widget_tweaks %}
{% block page-title %} 
<title>Arte'Venue | Artist Artworks</title>
{% endblock page-title %} 
{% block page-description %}
<meta name="description" content="Arte'Venue | Artist Artworks">
{% endblock page-description %}
{% block page-keywords %}
<meta name="keywords" content="Artist artworks, artevenue, original artwork">
{% endblock page-keywords %}


{% block coursel-stylesheet %}
{% endblock coursel-stylesheet %}

{% block jqueryui-script %}
{% endblock jqueryui-script %}

{% block coursel-script %}
{% endblock coursel-script %}

{% block front.js %}
{% endblock front.js %}

{% block imagemap-resize-script %}
{% endblock imagemap-resize-script %}

{% block google-recaptcha-3 %}
{% endblock google-recaptcha-3 %}

	<!-- Only Override the site content block -->
	{% block sitecontent %}
        <div class="container mb-5">
			<div class="row">
				<!-- breadcrumb-->
				<div class="col-12">
					<nav aria-label="breadcrumb">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
						<li class="breadcrumb-item"><a href="{% url 'artist_page' %}">Artist's Page</a></li>
							<li aria-current="page" class="breadcrumb-item active">Artworks List</li>
						</ol>
					</nav>
				</div>
			</div>

			{% if msg %}
			<div class="row">
				<div class="col-12 text-center" style = "background-color: #add8e6; color:red; padding:5px; font-weight:600;">
					{{msg}}
				</div>
			</div>
			{% endif %}							
			<div class="row">
				<div class="col-12 text-center">
					<h1>LIST OF ALL ARTWORKS</h1>
				</div>
			</div>
			
			<div class="row">
				<div class = "col-12">
					<div class="panel-group">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title" style = "background-color: #f9f9f9; 
										padding:15px;">
									<a data-toggle="collapse" href="#collapse1" style = "text-decoration: underline;">
										<strong><i class = "fa fa-filter fa-lg"> </i> FILTER</strong>
									</a>
									{% if filter_applied %}<span class="pull-right" style = "color: #11b6bd;"><i class = "fa fa-exclamation" style = "color: red;"></i> Filter(s) are applied</span>{% endif %}
								</h4>
							</div>
							<form method = 'POST'>
							{% csrf_token %}
							<div id="collapse1" class="panel-collapse collapse">
								<div class="panel-body">
									<div class="row">
										<div class = "col-6 col-md-3">
										  <div class="form-group">
											<label for="fromdate">Uploaded Date From:</label>
											<input type="date" class="form-control" id="fromdate" name="fromdate" value = "{{startDt|date:'Y-m-d'}}">
										  </div>										
										</div>
										<div class = "col-6 col-md-3">
										  <div class="form-group">
											<label for="todate">To:</label>
											<input type="date" class="form-control" id="todate" name="todate" value = "{{endDt|date:'Y-m-d'}}">
										  </div>										
										</div>
										<div class = "col-6 col-md-2">
										  <div class="form-group">
											<label for="order_namber">Artwork ID:</label>
											<input class="form-control" id="part_number" name="part_number" value = "{{part_number}}">
										  </div>										
										</div>
										<div class = "col-6 col-md-2">
										  <div class="form-group">
											<label for="order_namber">Title Like:</label>
											<input class="form-control" id="title" name="title" value = "{{title}}">
										  </div>										
										</div>
										<div class = "col-6 col-md-2">
											<span style = "text-decoration: underline; cursor: pointer;" onclick="clearFilters();">Clear All Filters</span> 
											<button class = "btn btn-primary mt-2" type = "submit">Submit</button>
										</div>
										<div class = "col-12">
											<hr>
										</div>
									</div>
								</div>
							</div>
							</form>
						</div>
					</div>				
				</div>
			</div>
			
			<div class="row">
				<div class="col-12" style = "color:#11b6bd;">
				{% if artworks %}
					({{artworks.count}} artworks found)
				{% else	%}
					(No artwork found)
				{% endif %}
				</div>
			</div>
			
			
			{% for a in artworks %}
			<div class = "box mb-4" id = "box_{{a.product.part_number}}" style = "padding-top:0px; background-color:#f9f9f9;">
				<div class="row d-flex d-align-items-center" style = "background-color:#f6f6f6; padding:10px;">
					<div class="col-12" style = "color:#11b6bd;">
						<h3> <strong>ARTWORK ID: {{a.product.part_number}}</strong> <span style = "font-size: 0.75rem;">, Upload Dt: {{a.uploaded_date|date:'d/M/y'}}</span></h3>
					</div>
					<div class="col-12" style = "color:#11b6bd;">
						<strong>
						STATUS: 
						{% if a.unapproved %}
							<span style = "color:orange;">Not Approved for Sell - {{a.get_unapproval_reason_display}}</span>
						{% else %}
							{% if a.artist_listed %}
								{% if a.approved %}
									<span style = "color:green;">Listed for sell.</span>
								{% else %}
									Pending Arte'Venue approval.
								{% endif %}
							{% else %}
								Not submitted for Arte'Venue review.
							{% endif %}
						{% endif %}
						</strong>
					</div>
				</div>
				<div class="row mt-3">
					<div class = "col-12 col-md-6">
						{% if a.product.high_resolution_url %} 
						<img src = "{% static a.product.high_resolution_url %}" alt="Artist Artwork Image" 
							width=250 style="">
						{% else %}
						<img src = "{% static 'img/custom_framing/upload_icon.png' %}" alt="Upload Image Icon" 
							width=100 style="top: 25%; position: absolute;left: 25%;">
						<h3>High resolution artwork image not uploaded</h3>
						{% endif %}
					</div>
					<div class = "col-12 col-md-6">
						<div class = "row">
							<div class = "col-6">
								Title: {{a.product.name}}
							</div>
							<div class = "col-6">
								Price: {{a.product.original_art_price|floatformat}}
							</div>
							<div class = "col-6 pull-left">
								Medium: {{a.product.get_art_medium_display}}
							</div>
							<div class = "col-6 pull-right">
								TYPE: {% if a.product.image_type == '0' %} PAINTING {% else %} PHOTOGRAPH {% endif %}
							</div>
							<div class = "col-6">
								Surface: {{a.product.get_art_surface_display}}
							</div>
							<div class = "col-6 pull-left">
								Size: {{a.product.art_width}}" X {{a.product.art_height}}"
							</div>
							<div class = "col-12 pull-left">
								Sell Mode: {% if a.sell_mode == 'O' %} Original Art Only  {% endif %}{% if a.sell_mode == 'A' %}  Art Print Only  {% endif %}{% if a.sell_mode == 'B' %} Original and Art Print {% endif %}
							</div>
							<div class = "col-12 pull-left">
								Art Print Max Size: {{a.product.max_width}}" X {{a.product.max_height}}"
							</div>
						</div>
						<div class="row text-center">
							<div class = "col-12 col-md-6 mt-3">
								<a class = "btn btn-secondary" 
									href = "{% url 'delist_artwork' a.product.part_number %}" >
									Delist
								</a><br />
								Stop selling this artwork
							</div>
							{% if a.unapproved %}
								{% if a.unapproval_reason == 'X' %}
									<div class = "col-12 col-md-6 mt-3">
										Arte'Venue art review team does not find this artwork fit for sell on our platform.
									</div>
								{% else %}
									<div class = "col-12 col-md-6 mt-3">
										<a class = "btn btn-primary"
											href = "{% url 'upload_art' a.product.part_number %}">
											Update
										</a> <br />
										Update size, price, etc. Or change the image.
									</div>
								{% endif %}
							{% else %}
								<div class = "col-12 col-md-6 mt-3">
									<a class = "btn btn-primary"
										href = "{% url 'upload_art' a.product.part_number %}">
										Update
									</a> <br />
									Update size, price, etc. Or change the image.
								</div>
							{% endif %}
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		{% include 'artevenue/message-modal_ok.html' %}		

	{% endblock sitecontent %}
	
	{% block jscripts %}	
	<script>
		$( document ).ready(function() {
		});	
	</script>
	<script>
		function clearFilters(){
		
			$("#fromdate").val('');
			$("#todate").val('');
			$("#part_number").val('');
			$("#title").val('');
			
		}	
	</script>
	{% endblock jscripts %}
			
	{% block tawkto %} 
	{% endblock tawkto %} 		