blog/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

from django.contrib.auth import views as auth_views
from allauth.account.views import LoginView

from django.contrib.sitemaps.views import sitemap


urlpatterns = [
	
	#url(r'^artist_signup/$', views.register_as_artist, name='artist_signup'),
	url(r'^blog/$', views.blog, name='blog'),
	path('get-blog/<int:post_id>', views.get_blog, name='get_blog'),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

estore/urls.py
from django.contrib import admin
from django.conf.urls import include, url

from django.urls import path

from rest_framework import routers
from artevenue.views import api_views

router = routers.DefaultRouter()
router.register(r'homelane', api_views.Homelane_dataViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('artevenue.urls')),
    url('^', include('artist.urls')),
	url('^', include('review.urls')),
    url('^', include('gallerywalls.urls')),
    url('^', include('returns.urls')),
    url('^', include('av_products.urls')),
    url('^', include('spinwheel.urls')),
	url(r'', include('webmaster_verification.urls')),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	
	url(r'^tinymce/', include('tinymce.urls')),
    url('^', include('blog.urls')),	
]

returns/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

from django.contrib.auth import views as auth_views
from allauth.account.views import LoginView

urlpatterns = [
	
	url(r'^orders-returns/$', views.initiate_returns, name='initiate_returns'),
	url(r'^ajax/get-orders-for-returns/$', views.get_orders_for_returns, name='get_orders_for_returns'),
	url(r'^choose-products-for-return/$', views.choose_products_for_return, name = 'choose_products_for_return'),
	url(r'^process-returns/$', views.process_returns, name = 'process_returns'),
	url(r'^cancel-return-request/$', views.cancel_return_request, name = 'cancel_return_request'),
	url(r'^get-active-return-request/$', views.get_active_return_requests, name = 'get_active_return_request'),
	path('return-request-for-update/<int:ret_id>/', views.return_request_for_update, name = 'return_request_for_update'),
	url(r'^update-return-req-status/$', views.update_return_req_status, name = 'update_return_req_status'),
	url(r'^returns-report/$', views.returns_report, name = 'returns_report'),
	url(r'^ajax/get-returns-report/$', views.get_returns_report, name='get_returns_report'),
	
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

returns/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

from artevenue.models import Order, Product_view, Promotion, Moulding, Print_medium, Mount
from artevenue.models import Acrylic, Stretch, Board, Product_type, Order_items_view
from artevenue.models import Shipping_method, Shipper, Shipping_status
from artevenue.models import Stock_image, User_image, Stock_collage, Original_art
from artevenue.models import Cart_item, Product_view, Promotion


class Credit_note(models.Model):	
	CRN_REASON = (
		('UN', 'Not Specified'),
		('RT', 'Full Refund Issued for Customer Return'),
		('DM', 'Full Refund Issued for Damaged Delivery'),
		('PR', 'Partial Refund for Damaged Delivery'),
		('PC', 'Partial Refund for Customer Return'),
		('CA', 'Reduced Price Due to Changes to Artwork'),
		('RM', 'Artwork Removed from the Order'),
		('AD', 'Additional Discount Offered'),
		('CN', 'Order Cancelled'),
	)    

	crn_id = models.AutoField(primary_key=True)
	credit_note_number = models.CharField(max_length = 15, blank = True, default = '')
	credit_note_date = models.DateTimeField(null=True)
	order = models.ForeignKey(Order,on_delete=models.PROTECT, null=False)
	credit_note_amount = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	credit_note_reason = models.CharField(max_length = 2, choices=CRN_REASON, blank=True, default = '')
	remarks = models.CharField(max_length = 500, blank = True, default = '')
	created_date = models.DateTimeField(auto_now_add=True, null=False)	
	updated_date = models.DateTimeField(auto_now=True, null=False)	


class Credit_note_detail(models.Model):	
	crn_detail_id = models.AutoField(primary_key=True)
	credit_note = models.ForeignKey(Credit_note,on_delete=models.PROTECT, null=True)
	product_id = models.IntegerField(null=False)   ## To be referenced to Product_view
	promotion = models.ForeignKey(Promotion, models.PROTECT, null=True)
	quantity = models.IntegerField(null=False)
	item_unit_price = models.DecimalField(max_digits=12, decimal_places=2, null=False, default=0)
	item_sub_total = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	item_disc_amt  = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	item_tax  = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	item_total = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	moulding = models.ForeignKey(Moulding,on_delete=models.PROTECT, null=True)
	moulding_size = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	print_medium = models.ForeignKey(Print_medium, models.PROTECT, null=False, default='PAPER')
	print_medium_size = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	mount = models.ForeignKey(Mount, models.PROTECT, null=True)
	mount_size = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	board = models.ForeignKey(Board, models.PROTECT, null=True)
	board_size = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	acrylic = models.ForeignKey(Acrylic, models.PROTECT, null=True)
	acrylic_size = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	stretch = models.ForeignKey(Stretch, models.PROTECT, null=True)
	stretch_size = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	image_width = models.DecimalField(max_digits=3, decimal_places=0, blank=False, null=False)
	image_height = models.DecimalField(max_digits=3, decimal_places=0, blank=False, null=False)	
	product_type = models.ForeignKey(Product_type, models.PROTECT, null=False) 
	created_date = models.DateTimeField(auto_now_add=True, null=False)	
	updated_date = models.DateTimeField(auto_now=True, null=False)	


class Debit_note(models.Model):	
	DRN_REASON = (
		('UN', 'Not Specified'),
		('CA', 'Increased Price Due to Changes to Artwork'),
		('AA', 'Additional Artwork Added to the Order'),
		('AF', 'Increased Price Due to Additional Framing'),
		('OT', 'Increased Price Due to Other Changes'),
	)    

	drn_id = models.AutoField(primary_key=True)
	debit_note_number = models.CharField(max_length = 15, blank = True, default = '')
	debit_note_date = models.DateTimeField(null=True)
	order = models.ForeignKey(Order,on_delete=models.PROTECT, null=False)
	debit_note_amount = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	debit_note_reason = models.CharField(max_length = 2, choices=DRN_REASON, blank=True, default = '')
	remarks = models.CharField(max_length = 500, blank = True, default = '')
	created_date = models.DateTimeField(auto_now_add=True, null=False)	
	updated_date = models.DateTimeField(auto_now=True, null=False)	


class Debit_note_detail(models.Model):	
	drn_detail_id = models.AutoField(primary_key=True)
	debit_note = models.ForeignKey(Debit_note,on_delete=models.PROTECT, null=True)
	product_id = models.IntegerField(null=False)   ## To be referenced to Product_view
	promotion = models.ForeignKey(Promotion, models.PROTECT, null=True)
	quantity = models.IntegerField(null=False)
	item_unit_price = models.DecimalField(max_digits=12, decimal_places=2, null=False, default=0)
	item_sub_total = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	item_disc_amt  = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	item_tax  = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	item_total = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	moulding = models.ForeignKey(Moulding,on_delete=models.PROTECT, null=True)
	moulding_size = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	print_medium = models.ForeignKey(Print_medium, models.PROTECT, null=False, default='PAPER')
	print_medium_size = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	mount = models.ForeignKey(Mount, models.PROTECT, null=True)
	mount_size = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	board = models.ForeignKey(Board, models.PROTECT, null=True)
	board_size = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	acrylic = models.ForeignKey(Acrylic, models.PROTECT, null=True)
	acrylic_size = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	stretch = models.ForeignKey(Stretch, models.PROTECT, null=True)
	stretch_size = models.DecimalField(max_digits=12, decimal_places=2, null=True)
	image_width = models.DecimalField(max_digits=3, decimal_places=0, blank=False, null=False)
	image_height = models.DecimalField(max_digits=3, decimal_places=0, blank=False, null=False)	
	product_type = models.ForeignKey(Product_type, models.PROTECT, null=False) 
	created_date = models.DateTimeField(auto_now_add=True, null=False)	
	updated_date = models.DateTimeField(auto_now=True, null=False)	

class Return_order(models.Model):	
	RET_REASON = (
		('UN', 'Not Specified'),
		('Q', 'Quality Issue'),
		('D', 'Damaged Delivery'),
		('S', 'Size Issue'),
		('N', "Don't Need It"),
		('L', 'Did not Like It'),
	)    
	RET_STATUS = (
		('X', 'Request Cancelled'),
		('0', 'Request Raised'),
		('1', 'Request Being Processed'),
		('2', 'Shipment Booked'),
		('3', 'Shipment Picked Up'),
		('4', 'Shipment Received by ArteVenue'),
		('5', 'Quality Check In Process'),
		('6', 'Quality Check Failed'),
		('7', 'Quality Check Passed'),
		('8', 'Refund Issued'),
		('9', 'Request Closed'),
	)
	CLOSURE_STATUS  = (
		('0', 'Return Request Cancelled'),
		('1', 'Quality Check Failed'),
		('2', 'Refund Issued'),
	)
	ret_id = models.AutoField(primary_key=True)
	ret_number = models.CharField(max_length = 15, blank = True, default = '')
	ret_request_date = models.DateTimeField(null=True)
	ret_reason = models.CharField(max_length = 2, choices=RET_REASON, blank=True, default = '')
	order = models.ForeignKey(Order,on_delete=models.PROTECT, null=False)
	return_shipment_charges = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	other_deductions = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	total_deductions = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	refund_amount = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	refund_transaction_reference = models.CharField(max_length = 500, blank = True, default = '')
	remarks = models.CharField(max_length = 5000, blank = True, default = '')
	ret_process_date = models.DateTimeField(null=True)
	ret_shipping_method = models.ForeignKey(Shipping_method, models.PROTECT, null=True) #Null is allowed, in case it's a store pickup
	ret_shipper = models.ForeignKey(Shipper, models.PROTECT, null=True) #Null is allowed, in case it's a store pickup	
	ret_shipping_status = models.ForeignKey(Shipping_status, models.PROTECT, null=True) #Null is allowed, in case it's a store pickup
	ret_status = models.CharField(max_length = 2, blank=True, 
		choices=RET_STATUS, default='0') 
	closure_status = models.CharField(max_length = 2, blank=True,
		choices=CLOSURE_STATUS, default='') 
	created_date = models.DateTimeField(auto_now_add=True, null=False)	
	updated_date = models.DateTimeField(auto_now=True, null=False)	


class Return_order_item(models.Model):	
	QC_FAIL_REASON = (
		('DM', 'Products Received in Damanged Condition'),
		('WR', 'Products Received Are Not As Per The Order')
	)
	ret_item_id = models.AutoField(primary_key=True)
	return_order = models.ForeignKey(Return_order, on_delete=models.PROTECT, null=True)
	order_item_id = models.IntegerField(null=False)   ## Referential relation to Order_items_view (programatically)

	ret_item_quantity = models.IntegerField(null=False)
	ret_item_unit_price = models.DecimalField(max_digits=12, decimal_places=2, null=False, default=0)
	ret_item_sub_total = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)
	ret_item_disc_amt  = models.DecimalField(max_digits=12, decimal_places=2,  null=False, default=0)

returns/templates/returns/list_of_active_returns.html
{% extends 'artevenue/estore_base.html' %}
{% load static %}
{% load utils %}

{% block page-title %} 
<title>Arte'Venue | Store Orders</title>
{% endblock page-title %} 
  
{% block page-description %}
<meta name="description" content="Arte'Venue | Returns Requests">
{% endblock page-description %}
  
{% block page-keywords %}
<meta name="keywords" content="artevenue, returns">
{% endblock page-keywords %}
  
{% block page-author %}
<meta name="author" content="Arte'Venue">
{% endblock page-author %}

{% block coursel-stylesheet %}
{% endblock coursel-stylesheet %}

{% block jqueryui-script %}
{% endblock jqueryui-script %}

{% block coursel-script %}
{% endblock coursel-script %}

{% block front.js %}
{% endblock front.js %}


{% block imagemap-resize-script %}
{% endblock imagemap-resize-script %}

	{% block sitecontent %}

    <div id="all">
		<div id="content">
			<div class="container mb-5">
				<div class = "row">
					<div class="col-12">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
								<li class="breadcrumb-item"><a href="{% url 'staff_page' %}">Staff Page</a></li>
								<li aria-current="page" class="breadcrumb-item active">List of Active Return Requests</li>
							</ol>
						</nav>
					</div>
				</div>
				<div class = "row">				
					<div class = "col-12 text-center">
						<h2 style = "font-weight:700;">ACTIVE RETURN REQUESTS</h2> 
					</div>
				</div>
				<div class = "row">				
					<div class = "col-12">
						Total Active Returns: {{returns.count|floatformat|default_if_none:0}}
					</div>
				</div>						
				<div class="row mt-2">
					<div class = "col-12">
						<table id = "ordTbl" class="table table-responsive table-striped">
							<thead>
								<tr>
									<th width="20%">Customer Name</th>
									<th width="10%" style = "text-align:right">Refund Amount Due</th>
									<th width="10%" style="text-align:right">Ret Req No.</th>
									<th width="10%" style="text-align:right">Ret Req Dt.</th>
									<th width="15%">Status</th>
									<th width="25%">Remarks</th>
									<th width="10%"></th>
								</tr>
							</thead>
							<tbody>
								{% for r in returns %}
								<tr>
									<td>
										<div class = "pull-left">
											{{r.order.order_billing.full_name}}
										</div>
									</td>
									<td style = "text-align:right">
										{{r.refund_amount|floatformat}}
									</td>
									<td style = "text-align:right">
										{{r.ret_number}}
									</td>
									<td style = "text-align:right">
										{{r.ret_request_date|date:'d-M-y'}}
									</td>
									<td>
										{{r.get_ret_status_display}}
									</td>
									<td>
										{{r.remarks}}
									</td>
									<td style = "text-align:right">
										<a class="btn btn-link btn-sm btn-primary" href="{% url 'return_request_for_update' r.ret_id %}">
											Update Status
										</a>
									</td>
								</tr>
								{% endfor %}
								
							</tbody>
						</table>
					</div>
				</div>
				<hr>
			</div>
		</div>
	</div>
	{% endblock sitecontent %}

	{% block jscripts %}
	<script>
		$("#id_req_date").change(function(){
			$("#req_date").val( $(this).val() );
		});
		$("#id_remarks").change(function(){
			$("#remarks").val( $("#remarks").val() + $(this).val() );
		});
	
		$(".item-chk").change(function(){
			$("#selected_items").val('');
			{% for i in choose_order_items %}
				if ($("#chk_{{i.order_item_id}}").prop("checked") == true) {
					var v = $("#selected_items").val();
					$("#selected_items").val(v + "{{i.order_item_id}},");
				}
			{% endfor %}
		});
	
		$("#id_ret_reason").change(function(){
			$("#ret_reason").val( $(this).val() );
		});
		
	</script>
	<script>
		$( document ).ready(function() {
			var today = new Date();
			var to_dt = today.getDate();
			var to_mn = today.getMonth();
			var to_mn = to_mn + 1;
			var to_yy = today.getFullYear();						
			$("#id_req_date").val( parseInt(to_yy) + "-" + zeroPad(to_mn) + "-" + zeroPad(to_dt) );
			$("#req_date").val( parseInt(to_yy) + "-" + zeroPad(to_mn) + "-" + zeroPad(to_dt)  );
			$("#ret_reason").val( $("#id_ret_reason").val() );
			
			// Mark items already initiated for return
			{% for i in ret_order_items %}
				$("#chk_{{i.order_item_id}}").prop( "checked", true );
				$("#selected_items").val($("#selected_items").val() + "{{i.order_item_id}},");
				//Items previously selected for returns
				$("#ini_items").val($("#ini_items").val() + "{{i.order_item_id}},");
				$("#ret_reason").val( "{{i.return_order.ret_reason}}" );
				$("#id_ret_reason").val( "{{i.return_order.ret_reason}}" );
				$("#req_date").val( "{{i.return_order.ret_request_date|date:'Y-m-d'}}" ); 
				$("#id_req_date").val( "{{i.return_order.ret_request_date|date:'Y-m-d'}}" ); 
				$("#refund_amount").val("{{ret_order.refund_amount}}");
				$("#id_remarks").val("{{ret_order.remarks}}");
				calcRefund();
			{% endfor %}
			
			{% if ret_order.ret_status > '2' %}
				doNotModify();
			{% endif %}
		});

		function zeroPad(val){
			if(val < 10){
				ret = "0" + String(val);
			} else {
				ret = String(val);
			}
			return ret;
		}
		
		function doNotModify(){
			$("#btn-submit").prop('disabled', true);
			$("#check-all").prop('disabled', true);
			{% for i in choose_order_items %}
				$("#chk_{{i.order_item_id}}").prop('disabled', true);			
			{% endfor %}
			$("#id_ret_reason").prop('disabled', true);
			$("#id_req_date").prop('disabled', true);		
		}
	</script>
	
	<script>
		$('#check-all').change(function() {
			$("#selected_items").val('');
			if(this.checked) {			
				{% for i in choose_order_items %}
					$("#chk_{{i.order_item_id}}").prop('checked', true);
					$("#selected_items").val($("#selected_items").val() + "{{i.order_item_id}},");
				{% endfor %}
			} else {
				{% for i in choose_order_items %}
					$("#chk_{{i.order_item_id}}").prop('checked', false);
				{% endfor %}			
				$("#selected_items").val("");
			}			
			calcRefund();
		});
		
		$( ".item-chk" ).change(function() {
		  calcRefund();
		  
		  if(this.checked == false) {
				$('#check-all').prop('checked', false);
			}
		});		
		
		function calcRefund(){
			var amt = 0;
			var cnt = 0;
			var itms = '';
			{% for i in choose_order_items %}
				if ($("#chk_{{i.order_item_id}}").prop("checked") == true) {
					amt = amt + {{i.item_total}};
					cnt = cnt + 1;
					itms = itms + ", " + String({{i.order_item_id}});
				}
				$("#refund-due").html(amt);
				$("#refund_amount").val(amt);
				$("#sel-cnt").html(cnt);
			{% endfor %}
		}
	</script>

	<script>
		function validateRet(){
			var cnt = parseInt($("#sel-cnt").html());
			if (isNaN(cnt)){
				alert("Please selects products for return");
				return false;
			}
			
			if (cnt < 1){
				alert("Please selects products for return");
				return false;
			}
			
			if (confirm('Are you sure you want to process this return?')) {
			   return true;
			} else {
			   return false;
		   }
		}
	</script>
		
	{% endblock jscripts %}

returns/templates/returns/return_request_update_confirm.html
{% extends 'artevenue/estore_base.html' %}
{% load static %}

{% block page-title %} 
<title>Arte'Venue | Returns Status Update</title>
{% endblock page-title %} 
  
{% block page-description %}
<meta name="description" content="Arte'Venue | Return Req Status Update">
{% endblock page-description %}
  
{% block page-keywords %}
<meta name="keywords" content="artevenue, returns update confirm ">
{% endblock page-keywords %}
  
{% block page-author %}
<meta name="author" content="Arte'Venue">
{% endblock page-author %}

{% block coursel-stylesheet %}
{% endblock coursel-stylesheet %}

{% block jqueryui-script %}
{% endblock jqueryui-script %}

{% block coursel-script %}
{% endblock coursel-script %}

{% block front.js %}
{% endblock front.js %}


{% block imagemap-resize-script %}
{% endblock imagemap-resize-script %}

{% load widget_tweaks %}
	<!-- Only Override the site content block -->
	{% block sitecontent %}

    <div id="all">
		<div id="content">
			<div class="container">
				<div class = "row">
					<div class="col-12">
						<!-- breadcrumb-->
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
								<li class="breadcrumb-item"><a href="{% url 'staff_page' %}">Staff Page</a></li>
								<li class="breadcrumb-item"><a href="{% url 'get_active_return_request' %}">Update Return Requests</a></li>
								<li aria-current="page" class="breadcrumb-item active">Return Request Status Updated</li>
							</ol>
						</nav>
					</div>
				</div>
				<div class = "row">				
					{% if not err_flag %}
						<div class = "col-12 text-center">
							<h1 style = "font-weight:700;">RETURN REQUEST STATUS UPDATED</h1>
						</div>				
					{% else %}
						<div class = "col-12 text-center">
							<h1 style = "font-weight:700; color: red;">{{err_msg}} | REQUEST NOT UPDATED. PLS PROCESS AGAIN. 
							<a href = "<{% url 'return_request_for_update' ret.ret_id %}">Click here</a> </h1>
						</div>		
					{% endif %}
					<div class = "col-12 text-center mt-5">
						Return Request for Order No: {{ret.order.order_number}}, dated : {{ret.order.order_date|date:"d m Y"}}  | Status: {{ ret.order.get_order_status_display }} 
					</div>
					<div class= "col-12">
						<h4>
						{% if ret.order.order_status == 'CO' %}
							{% if ret.order.delivery_date %}
								on {{ret.order.delivery_date | date:'d-M-Y'}}
							{% endif %}
						{% endif %}
						{% if ret.order.order_status == 'IN' %} 
							{% if ret.order.tracking_number %} 
								<h4> Order Tracking:<br />
								{% if ret.order.shipper %}
									Shipped by: {{ ret.order.shipper.name }}, 
								{% endif %}
								Tracking no.: {{ ret.order.tracking_number }} <br />
								{% if ret.order.tracking_url %}
								Tracking url: <a href = "{{ ret.order.tracking_url }}" target="_blank">Click to Track</a>
								{% endif %}
								</h4>
							{% endif %}
						{% endif %}
					</div>
					
					<div class = "col-12 text-center mt-3">
						<strong>RETURN REQUEST NO: {{ret.ret_number}}</strong>
						| <strong>STATUS: {{ret.get_ret_status_display}}</strong>
					</div>
				</div>
				{% include 'returns/return_req_for_update_table.html' %}

				<div class = "row mb-4">				
					<div class = "col-6 col-md-4 text-center">
						<a class = "btn btn-primary" href = "{% url 'index' %}">Go to Home Page</a>
					</div>
					<div class = "col-6 col-md-4 text-center">
						<a class = "btn btn-primary" href = "{% url 'staff_page' %}">Go back to Staff Page</a>
					</div>
				</div>
			</div>
        </div>
    </div>
	{% endblock sitecontent %}


	{% block jscripts %}	
	<script>
		$( document ).ready(function() {
 			$body = $("body");
			$(document).on({
				ajaxStart: function() { $body.addClass("loading");    },
				ajaxStop: function() { $body.removeClass("loading"); }    
			});		
		});
	</script>

	{% endblock jscripts %}

returns/templates/returns/returns_report_table.html
{% load static %}
{% load utils %}

	<div class = "row mb-3">
		<div class = "col-6 col-md-4">
			<strong>Number of Return Requests: {{ ret_orders.count | floatformat}}</strong>
		</div>
		<div class = "col-6 col-md-4">
			{% if totals.order_total__sum %}
			<strong>Total Refund Amount: {{totals.order_total__sum|default_if_none:'0'|floatformat|indian_number_format}}</strong>
			{% endif %}
		</div>
		<div class = "col-6 col-md-4">
			{% if totals.order_total__avg %}
			<strong>Avg Refund Amount: {{ totals.order_total__avg|default_if_none:'0'|floatformat|indian_number_format}}</strong>
			{% endif %}		
		</div>
	</div>
	
	<div class="table table-responsive">
		<table id = "ordTbl" class="table table-responsive table-striped">
			<thead>
				<tr>
					<th width="9%">Return No.</th>
					<th width="9%">Return Dt.</th>
					<th width="13%">Status</th>
					<th width="13%">Reason</th>
					<th width="9%">Ord No.</th>
					<th width="9%">Ord Dt.</th>
					<th width="11%">Cust Name</th>
					<th width="9%">City</th>
					<th width="9%">State</th>
					<th width="9%" style="text-align:right">Ref Amount</th>
				</tr>
			</thead>
			<tbody>
				{% for ro in ret_orders %}
				<tr>
					<td>
						{{ro.ret_number }}
					</td>																						
					<td>
						{{ro.ret_request_date|date:'d/m/y'}}
					</td>																						
					<td>
						{{ro.get_ret_status_display}}
					</td>																						
					<td>
						{{ro.get_ret_reason_display}}
					</td>																						
					<td>
						{{ro.order.order_number}}
					</td>
					<td>
						{{ro.order.order_date | date:'d/m/y'}}
					</td>
					<td>
						{{ro.order.order_billing.full_name }}
					</td>																						
					<td>
						{{ro.order.order_billing.city}}
					</td>
					<td>
						{{ro.order.order_billing.state_id}}
					</td>
					<td style = "text-align:right">{{ro.refund_amount|floatformat}}</td>

				</tr>
				{% endfor %}
			</tbody>
			<tfoot>
			</tfoot>
		</table>
	</div>
	<div class = "mb-5" style="padding-bottom:2px; background-color:#11b6bd;" >
	</div>							
	